export const ADMIN_ROUTE =  '/'
export const LOGIN_ROUTE =  '/login'
export const REGISTRATION_ROUTE =  '/registration'
export const LANDING_PAGE =  '/'
export const BASKET_ROUTE =  '/basket'
export const PRODUCT_ROOUTE = '/product'
export const CATALOG_ROUTE = '/catalog'
export const PRODUCT_SEARCH = '/searchProducts'
export const FAVORITE_ROUTE = '/favorite'

